<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <GlobalPackageReference Include="Umbraco.GitVersioning.Extensions" Version="0.2.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="18.7.1" />
    <PackageVersion Include="NJsonSchema" Version="11.6.1" />
    <PackageVersion Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>
</Project>