<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <Title>Umbraco JSON schema extensions</Title>
    <Description>MSBuild tasks for Umbraco to add JSON schema references, update JSON properties, and generate JSON schemas from .NET types.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Umbraco.JsonSchema.Extensions.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="NJsonSchema" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net10.0'" />
    <PackageReference Include="System.Text.Json" PrivateAssets="all" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>

  <!-- JsonSchemaGenerate is a net10.0 only task -->
  <ItemGroup Condition="'$(TargetFramework)' != 'net10.0'">
    <Compile Remove="JsonSchemaGenerate\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\**" Pack="true" PackagePath="build" />
  </ItemGroup>

  <!-- Package the task for distribution, see: https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#package-the-task-for-distribution -->
  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>NU5100;NU5128</NoWarn>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
  <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />
    </ItemGroup>
  </Target>
  <Target Name="AddBuildDependencyFileToBuiltProjectOutputGroupOutput" BeforeTargets="BuiltProjectOutputGroup" Condition="'$(GenerateDependencyFile)' == 'true'">
    <ItemGroup>
      <BuiltProjectOutputGroupOutput Include="$(ProjectDepsFilePath)" TargetPath="$(ProjectDepsFileName)" FinalOutputPath="$(ProjectDepsFilePath)" />
    </ItemGroup>
  </Target>
</Project>
