<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework /><!-- Clear the Directory.Build.props default to enable multi-targeting -->
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <Title>Umbraco JSON schema extensions</Title>
    <Description>Extensions for Umbraco to add JSON schema references and update JSON properties using MSBuild tasks.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="System.Text.Json" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net472'" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\**" Pack="true" PackagePath="build" />
  </ItemGroup>

  <!-- Package the task for distribution, see: https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#package-the-task-for-distribution -->
  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
    <NoWarn>NU5100;NU5128</NoWarn>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
  <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />
    </ItemGroup>
  </Target>
  <Target Name="AddBuildDependencyFileToBuiltProjectOutputGroupOutput" BeforeTargets="BuiltProjectOutputGroup" Condition="'$(GenerateDependencyFile)' == 'true'">
    <ItemGroup>
      <BuiltProjectOutputGroupOutput Include="$(ProjectDepsFilePath)" TargetPath="$(ProjectDepsFileName)" FinalOutputPath="$(ProjectDepsFilePath)" />
    </ItemGroup>
  </Target>

</Project>
